doseCalc/urls.py
from django.conf.urls import url

from . import views

app_name = 'doseCalc'
urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^submit/$', views.submit, name='submit'),
	url(r'^calculating/$', views.calculating, name='calculating'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
	url(r'^doseCalc/', include('doseCalc.urls')),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

doseCalc/models.py
from django.db import models

# Create your models here.

class Setup(models.Model):
	"""Class for setting up simulation parameters."""
	beamWidth = [0, 0]
	energy = 0
	nHistories = 0
	
	voxSize = [0, 0, 0]
	resolution = [0, 0, 0]
	scoringQuantity = ""
	CTFile = ""
	material=""

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def __str__(self):
		return self.question_text
	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text

doseCalc/forms.py
from django import forms

class CT(forms.Form):
	title = forms.CharField(max_length=50)
	file = forms.FileField()

doseCalc/views.py
from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import loader, RequestContext
from django.core.urlresolvers import reverse
from django.views import generic

from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.conf import settings

from .models import Setup
from .forms import CT
import os
import zipfile
import io

# Create your views here.
#def detail(request):
#	return HttpResponse("Dose calculation app.")

class IndexView(generic.TemplateView):
    model = Setup
    template_name = 'doseCalc/index.html'
	
	
	
def submit(request):	
	Setup.beamWidth[0] = float(request.POST.get('beamsize_x'))
	Setup.beamWidth[1] = float(request.POST.get('beamsize_y'))
	Setup.energy = float(request.POST.get('energy'))*12
	Setup.nHistories = int(request.POST.get('nhistories'))
	
	Setup.voxSize[0] = float(request.POST.get('voxsize_x'))
	Setup.voxSize[1] = float(request.POST.get('voxsize_y'))
	Setup.voxSize[2] = float(request.POST.get('voxsize_z'))
	Setup.resolution[0] = float(request.POST.get('resolution_x'))
	Setup.resolution[1] = float(request.POST.get('resolution_y'))
	Setup.resolution[2] = float(request.POST.get('resolution_z'))
	
	Setup.scoringQuantity = request.POST.get('scoring_quantity')
	
	Setup.CTFile = request.FILES.get('CT')
	if Setup.CTFile is not None:
		Setup.CTFile.name = "ctvolume.dat"
		path = default_storage.save('doseCalc/goCMC/'+Setup.CTFile.name, ContentFile(Setup.CTFile.read()))
	Setup.material = request.POST.get('material')
	
	return HttpResponseRedirect(reverse('doseCalc:calculating'))
	
def calculating(request):
	os.chdir("C:/Users/zhen/mysite1/mysite/doseCalc/goCMC")
	
	config = open("carbon_config", "w+")
	#config = open("test.txt", "w+")
	config.write('''// directory for macro cross section:
input/carbon.crossSection
// directory for mass stopping power ratio:
input/carbon.mspr
// directory for restricted stopping power in water:
input/carbon.rspw
// directory for nuclear data
input/nuclear
// beam parameters: width, energy, number of carbons, source center\n''')
	config.write("%f\t%f\n" % (Setup.beamWidth[0], Setup.beamWidth[1]))
	config.write("%f\n" % Setup.energy)
	config.write("%d\n" % Setup.nHistories)
	config.write("%f\t%f\t%f\n" % (0,0,-50))
	config.write("// phantom parameters: vox size, iso center, width, hight, depth\n")
	config.write("%f\t%f\t%f\n" % (Setup.voxSize[0],Setup.voxSize[1],Setup.voxSize[2]))
	config.write("%f\t%f\t%f\n" % (0,0,0))
	config.write("%d\t%d\t%d\n" % (Setup.resolution[0],Setup.resolution[1],Setup.resolution[2]))
	config.write("// CTFile or standard material:\n")
	if Setup.CTFile is not None:
		config.write(Setup.CTFile.name)
	else:
		config.write(Setup.material)
	config.write("\n// scoring quantity:\n")
	config.write(Setup.scoringQuantity)
	config.write('''
// output directory
Output/''')
	config.close()
	
	os.system('CLTransport.exe')
	
    # Files (local path) to put in the .zip
    # FIXME: Change this (get paths from DB etc)
	filenames = ["Output/"+Setup.scoringQuantity+"_mean.bin", "Output/"+Setup.scoringQuantity+"_std.bin"]

    # Folder name in ZIP archive which contains the above files
    # E.g [thearchive.zip]/somefiles/file2.txt
    # FIXME: Set this to something better
	zip_subdir = "Output"
	zip_filename = "%s.zip" % zip_subdir

    # Open StringIO to grab in-memory ZIP contents
	s = io.BytesIO()

    # The zip compressor
	zf = zipfile.ZipFile(s, "w")

	for fpath in filenames:
		# Calculate path for file in zip
		fdir, fname = os.path.split(fpath)
		zip_path = os.path.join(zip_subdir, fname)

        # Add file, at correct path
		zf.write(fpath, zip_path)

    # Must close zip for all contents to be written
	zf.close()

	# Grab ZIP file from in-memory, make response with correct MIME-type
	resp = HttpResponse(s.getvalue(), content_type = "application/x-zip-compressed")
	# ..and correct content-disposition
	resp['Content-Disposition'] = 'attachment; filename=%s' % zip_filename
	if Setup.CTFile is not None:
		os.remove(Setup.CTFile.name)
	os.chdir("C:/Users/zhen/mysite1/mysite")
	return resp
	

	

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.core.urlresolvers import reverse
from django.views import generic



from .models import Question, Choice

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
	
	
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

doseCalc/templates/doseCalc/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'doseCalc/index.css' %}" />
<script src="https://code.jquery.com/jquery-3.1.0.js" integrity="sha256-slogkvB1K3VOkzAI8QITxV3VzpOnkeNVsKvtkYLMjfk=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.15.1/jquery.validate.js"></script>
<script src="{% static 'doseCalc/index.js' %}"></script>

<h1>Dose calculation </h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form id="setup_form" action="{% url 'doseCalc:submit' %}" method="post" enctype="multipart/form-data">
{% csrf_token %}
<fieldset>
<legend>Source particle information:</legend>
Beam size (cm):<br>
<input type="text" name="beamsize_x" class="beamsize">
<input type="text" name="beamsize_y" class="beamsize"><br>
Beam energy (MeV/u):<br>
<input type="text" name="energy" id="energy"><br>
Number of histories:<br> 
<input type="text" name="nhistories"><br>
</fieldset>

<fieldset>
<legend>Phantom information:</legend>
Material:<br>
Please choose:
<input type="radio" id="CT_upload" class="phantom_material" name="phantom_material" value="upload">Upload a CT file
<input type="radio" id="standard_material" class="phantom_material" name="phantom_material" value="choose">Use standard material
<br>
<div id="CT_uploader">
<input type="file" name="CT"><br>
</div>
<div id="material_radio">
<input type="radio" name="material" value="WATER">
Water<br>
<input type="radio" name="material" value="PMMA">
PMMA
</div>
<br>
Voxel size (cm):<br>
<input type="text" name="voxsize_x" class="voxsize">
<input type="text" name="voxsize_y" class="voxsize">
<input type="text" name="voxsize_z" class="voxsize"><br>
Resolution:<br>
<input type="text" name="resolution_x" class="resolution">
<input type="text" name="resolution_y" class="resolution">
<input type="text" name="resolution_z" class="resolution">

</fieldset>


Scoring quantity:<br>
<input type="radio" name="scoring_quantity" value="DOSE2MEDIUM">
Dose to medium<br>
<input type="radio" name="scoring_quantity" value="DOSE2WATER">
Dose to water<br>
<input type="radio" name="scoring_quantity" value="FLUENCE">
Fluence<br>

<input type="submit" value="Submit" id="submit">
</form>

<div id="simulating">
Simulating<span class="dotting"></span>
</div>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>